/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleSurvey__factory } from "./SimpleSurvey__factory";
export { ZamaSurvey__factory } from "./ZamaSurvey__factory";
